"""schema inicial: agents, talent_bank, audit_logs, corporate_memory

Revision ID: 0001_schema_inicial
Revises:
Create Date: 2026-10-03 18:14:26.778497+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001_schema_inicial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('talent_bank',
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('role_title', sa.String(length=160), nullable=False),
    sa.Column('specialization', sa.String(length=240), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('tools', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('complexity', sa.Enum('TRIVIAL', 'SIMPLE', 'MODERATE', 'COMPLEX', 'CRITICAL', name='task_complexity'), nullable=False),
    sa.Column('recommended_model', sa.String(length=120), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_role', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_talent_bank')),
    sa.UniqueConstraint('slug', name='uq_talent_bank_slug')
    )
    op.create_index(op.f('ix_talent_bank_slug'), 'talent_bank', ['slug'], unique=False)
    op.create_table('agents',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('CEO', 'CTO', 'CMO', 'CFO', 'RA', 'SUBAGENT', name='agent_role'), nullable=False),
    sa.Column('agent_type', sa.Enum('CHIEF', 'SUBAGENT', name='agent_type'), nullable=False),
    sa.Column('status', sa.Enum('IDLE', 'WORKING', 'BLOCKED', 'TERMINATED', name='agent_status'), nullable=False),
    sa.Column('job_title', sa.String(length=160), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('estimated_ram_mb', sa.Integer(), nullable=False),
    sa.Column('reports_to_id', sa.Uuid(), nullable=True),
    sa.Column('talent_profile_id', sa.Uuid(), nullable=True),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('terminated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reports_to_id'], ['agents.id'], name=op.f('fk_agents_reports_to_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['talent_profile_id'], ['talent_bank.id'], name=op.f('fk_agents_talent_profile_id_talent_bank'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    op.create_index('ix_agents_role', 'agents', ['role'], unique=False)
    op.create_index('ix_agents_type_status', 'agents', ['agent_type', 'status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.Enum('NATURE_DECISION', 'NATURE_ALERT', 'AGENT_CREATED', 'AGENT_TERMINATED', 'AGENT_STATUS_CHANGED', 'MODEL_SELECTED', 'SYSTEM', name='audit_event_type'), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('resource_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_audit_logs_agent_id_agents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_actor', 'audit_logs', ['actor'], unique=False)
    op.create_index('ix_audit_logs_event_created', 'audit_logs', ['event_type', 'created_at'], unique=False)
    op.create_table('corporate_memory',
    sa.Column('memory_type', sa.Enum('DECISION', 'REPORT', 'MEETING', 'DIALOGUE', 'KNOWLEDGE', name='memory_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_agent_id', sa.Uuid(), nullable=True),
    sa.Column('author_role', sa.String(length=32), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_agent_id'], ['agents.id'], name=op.f('fk_corporate_memory_author_agent_id_agents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corporate_memory'))
    )
    op.create_index('ix_corporate_memory_importance', 'corporate_memory', ['importance'], unique=False)
    op.create_index('ix_corporate_memory_type_created', 'corporate_memory', ['memory_type', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_corporate_memory_type_created', table_name='corporate_memory')
    op.drop_index('ix_corporate_memory_importance', table_name='corporate_memory')
    op.drop_table('corporate_memory')
    op.drop_index('ix_audit_logs_event_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_agents_type_status', table_name='agents')
    op.drop_index('ix_agents_role', table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_talent_bank_slug'), table_name='talent_bank')
    op.drop_table('talent_bank')
    # ### end Alembic commands ###
